### ISSUE TITLE
Custom Range Slider Component

### ISSUE THREAD

**Issue by theBeginner86** [ALPHAVIO/Mirage-UI#100]
### Feature request-
Add a range slider component that gives the users full control over the range they can select for their particular use case.

### Additional context

https://user-images.githubusercontent.com/73700530/123051549-8a0b4080-d41f-11eb-9c63-69f1ad728151.mov

LGM-SOC

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by Pranav016** [comment]
I think this component is simple, it is directly available on Bootstrap's website thus we shouldn't add this as it is, maybe combined with some other component or in some other form factor. Re-open issue if needed.
Ref- https://getbootstrap.com/docs/5.0/forms/range/
