### ISSUE TITLE
Animated card stacks

### ISSUE THREAD

**Issue by Khushi-agarwal** [ALPHAVIO/Mirage-UI#102]
### Feature request
I would like to add animated cards stacks.

### Is your feature request related to a problem? Please describe. (optional)
A clear and concise description of what the problem is.

### Describe how this feature will be useful to the users/ contributors-
A clear and concise description of how this feature will be useful to our users/ contributors.

#### Are you contributing under any open-source program ?

LGM-SOC
<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
![animated-card-stacks](https://user-images.githubusercontent.com/76625662/123216159-da99a100-d4e6-11eb-940e-cc87ca5612ff.gif)

**Comment by riasenpai** [comment]
@Khushi-agarwal any updates regarding this issue?

**Comment by Khushi-agarwal** [comment]
> @Khushi-agarwal any updates regarding this issue?

Yes I am working on it. Will make a pr by tomorrow.

**Comment by riasenpai** [comment]
> > @Khushi-agarwal any updates regarding this issue?
> 
> Yes I am working on it. Will make a pr by tomorrow.

Sure!
