### ISSUE TITLE
Add background motion effect component

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/Mirage-UI#11]
### Feature request-
Add a simple and easy to use background motion effect component.

https://user-images.githubusercontent.com/54665036/120937593-03224c80-c72c-11eb-9915-727b138c939e.mp4

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by akshikamudgal** [comment]
For which page it has to be designed.

**Comment by Pranav016** [comment]
> For which page it has to be designed.

It's meant to be a reusable design component so just make a very simple page and implement this, so that other people can take the code and easily use them in their projects.
No specification in what kind of page or background etc.

**Comment by Sanyam17-beep** [comment]
hey @Pranav016 is it open to work

**Comment by Pranav016** [comment]
@Sanyam17-beep Please complete or unassign previously assigned issues and try to get not more than 2 issues assigned at the same time. You currently have 4 issues assigned so please unassign a couple issues

**Comment by Pranav016** [comment]
@Sanyam17-beep Please complete your previously assigned issues or unassign them so that others also get a chance. Try to have not more than 2 issues assigned at the same time, currently you have 4. Please unassign a couple

**Comment by Sanyam17-beep** [comment]
@Pranav016 i have unassigned it after this pr i have only two issue at  a time 
and sorry for this
