### ISSUE TITLE
Always moving Carousel

### ISSUE THREAD

**Issue by theBeginner86** [ALPHAVIO/Mirage-UI#118]
### Feature request-
Here, the carousel in a website should be moving constantly with sufficient speed so that the user is able to read the contents and doesn't need to bother about clicking the right/left button to see new testimonials.

### Additional context

https://user-images.githubusercontent.com/73700530/124150850-96426e00-daaf-11eb-942c-d38265316fe4.mov

LGM-SOC

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by riasenpai** [comment]
@Anupam-Panwar do  you have any updates regarding this issue?

**Comment by Anupam-Panwar** [comment]
@riasenpai I am facing some issues in the process of implementing this component 
If this component is in urgent need you may unassign me

**Comment by theBeginner86** [comment]
> @riasenpai I am facing some issues in the process of implementing this component
> If this component is in urgent need you may unassign me

No, it's not urgent until you are still working on it. If you want you may continue. 👍

**Comment by Anupam-Panwar** [comment]
> > @riasenpai I am facing some issues in the process of implementing this component
> > If this component is in urgent need you may unassign me
> 
> No, it's not urgent until you are still working on it. If you want you may continue. 👍

@theBeginner86 I am facing difficulty to implement this component 
thus it would be better if you may assign it to some other contributor

**Comment by saloni-15** [comment]
Do we have to add this carousel to a different folder or modify the previous one?
@theBeginner86

**Comment by theBeginner86** [comment]
> Do we have to add this carousel to a different folder or modify the previous one?
> @theBeginner86

you can add it to the same folder but with a specific name. Like `always-moving-carousel` or something of that sort. Basically, we are trying to have different forms of reusable components in this project, so the more variety we have the better it is. 👍
