### ISSUE TITLE
In buttons Glowing Gradient Fix

### ISSUE THREAD

**Issue by puneetkaur2929** [ALPHAVIO/Mirage-UI#119]
Hey @Pranav016 
As you can see glowing gradient is not working.
I am interested to fix this .
Kindly assign this issue to me under LGM SOC '21
![Screenshot (56)](https://user-images.githubusercontent.com/80326308/124175999-efb89600-dacb-11eb-8824-6a9fafa74065.png)

**Comment by theBeginner86** [comment]
@puneetkaur2929 
Yeah, you are correct. I just checked it out. (There are some minor issues with linking of the stylesheet) 🙂
Thanks for pointing it out. 👍

**From next time please make use of the issue template and don't alter it. It helps us to understand the problem better.
You can easily enter the parts of your issue into each sub-section.**
