### ISSUE TITLE
Add dynamic wave component

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/Mirage-UI#12]
### Feature request-

https://user-images.githubusercontent.com/54665036/120938947-07059d00-c733-11eb-852e-dd941af2a81e.mp4

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by Pranav016** [comment]
@SamikshaSankar are you still working on this ?

**Comment by Sanyam17-beep** [comment]
hey @theBeginner86 @Pranav016 can i work on this under lgmsoc

**Comment by theBeginner86** [comment]
> hey @theBeginner86 @Pranav016 can i work on this under lgmsoc

sure, go ahead. 👍
