### ISSUE TITLE
To fix mouse enter button

### ISSUE THREAD

**Issue by puneetkaur2929** [ALPHAVIO/Mirage-UI#120]
Hey @Pranav016
As you can see mouse enter button  is not working.
I am interested to fix this .
Kindly assign this  issue to me under LGM SOC '21
![Screenshot (57)](https://user-images.githubusercontent.com/80326308/124176492-956c0500-dacc-11eb-8d80-b3727219602b.png)

**Comment by theBeginner86** [comment]
@puneetkaur2929 
Yeah, you are correct. I just checked it out. (There are some minor issues with linking of the stylesheet) 🙂
Thanks for pointing it out. 👍

**From next time please make use of the issue template and don't alter it. It helps us to understand the problem better.
You can easily enter the parts of your issue into each sub-section.**
