### ISSUE TITLE
Button hover animation

### ISSUE THREAD

**Issue by Sanyam17-beep** [ALPHAVIO/Mirage-UI#128]
### Feature request-
Button Line Hover Animation

https://user-images.githubusercontent.com/84903641/124344352-32bf5a00-dbef-11eb-9c84-3f26eef0b9c4.mp4

#### Are you contributing under any open-source program ?

LGM-SOC

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by Sanyam17-beep** [comment]
hey @Pranav016  when will this issue be reviewed

**Comment by Sanyam17-beep** [comment]
hey @Pranav016 @theBeginner86 how do i add lgm soc label

**Comment by theBeginner86** [comment]
> hey @Pranav016 @theBeginner86 how do i add lgm soc label

See, in the issue template, there is a subsection that asks for the open-source program you are working with. In that you just have to write LGM-SOC then the bot will automatically assign the label for it.

Right now you have written LGM-SOC participant. Try changing it to LGM-SOC.
