### ISSUE TITLE
I would like to add loading Animation using html,css.

### ISSUE THREAD

**Issue by siddhi-244** [ALPHAVIO/Mirage-UI#129]
### Feature request-
I would like to add loading Animation using html,css which can be used as a preloader for any website.

### Describe how this feature will be useful to the users/ contributors-
It can be used as a preloader as well as it can be used while someone is fetching data and it takes time.

#### Are you contributing under any open-source program ?

Psoc.

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by siddhi-244** [comment]
Srry for the mistake sir would you please resolve my doubt here ?

**Comment by siddhi-244** [comment]
@Pranav016

**Comment by Pranav016** [comment]
I think a Fake Loader is already there in the repo, check here-
https://github.com/ALPHAVIO/Mirage-UI/tree/master/HTML%2BCSS%2BJS/Background

**Comment by siddhi-244** [comment]
Ok sir will add there. Thank you sir ! @Pranav016

**Comment by Pranav016** [comment]
> Ok sir will add there. Thank you sir ! @Pranav016

No I mean this is a repeated component, you can work on some other design. Otherwise same thing would be added twice.
This is same component you want to add - https://github.com/ALPHAVIO/Mirage-UI/tree/master/HTML%2BCSS%2BJS/Background/FakeLoader

**Comment by siddhi-244** [comment]
Mine is another one sir !

**Comment by Pranav016** [comment]
> Mine is another one sir !

Design might be different but it will be same as a Fake loader..
`It can be used as a preloader as well as it can be used while someone is fetching data and it takes time.` it will do the same work

**Comment by Pranav016** [comment]
You can add screenshots under this issue if the component is different then maintainers can check and approve the issue👍

**Comment by siddhi-244** [comment]
Ok will work on different animations

**Comment by siddhi-244** [comment]
> You can add screenshots under this issue if the component is different then maintainers can check and approve the issue👍

Ok sir
