### ISSUE TITLE
Add a simple vertical timeline component

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/Mirage-UI#13]
### Feature request-
Add a simple vertical timeline component with white background.

https://user-images.githubusercontent.com/54665036/120939014-59df5480-c733-11eb-8e1e-825b01b9126b.mp4

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by theBeginner86** [comment]
## Please comment within a day, if you are still working on this issue. If we don't get the response then we have to unassign this issue and give other contributors a chance. 😊🙂

**Comment by SamikshaSankar** [comment]
Yes I am working on it
