### ISSUE TITLE
Typewriter effect 

### ISSUE THREAD

**Issue by siddhi-244** [ALPHAVIO/Mirage-UI#130]
### Feature request-
Typewriter effect in css.

### Describe how this feature will be useful to the users/ contributors-
You can add this in your portfolio site to say hello to people or to make it more fascinating. 

#### Are you contributing under any open-source program ?

PSOC

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

https://user-images.githubusercontent.com/69195262/124346037-2bea1480-dbfa-11eb-89d0-8e5f59753963.mp4

**Comment by siddhi-244** [comment]
Shall I start working on it ? @Pranav016

**Comment by Pranav016** [comment]
First please check if the design component is already there in the repo and refrain from tagging any maintainers, we periodically review all the issues👍

Reference- https://github.com/ALPHAVIO/Mirage-UI/tree/master/HTML%2BCSS%2BJS/Text-Animations
