### ISSUE TITLE
Add different types of buttons effects

### ISSUE THREAD

**Issue by siddhi-244** [ALPHAVIO/Mirage-UI#133]
### Feature request-
Add different types of buttons effects

#### Are you contributing under any open-source program ?

PSOC

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

https://user-images.githubusercontent.com/69195262/124374127-4386d300-dcb6-11eb-9c36-b567044c0a31.mp4

**Comment by theBeginner86** [comment]
These buttons are cool but do check the buttons we already have at: https://github.com/ALPHAVIO/Mirage-UI/tree/master/HTML%2BCSS%2BJS/Buttons
I feel that we already have a few of those buttons. So, add those which we are not having already. 👍

**Comment by siddhi-244** [comment]
Sure sir

**Comment by siddhi-244** [comment]
https://user-images.githubusercontent.com/69195262/124380359-df760600-dcd9-11eb-916f-bb4ba14d499e.mp4

Sir tried these. Are these okayy ??

**Comment by Pranav016** [comment]
> /reviewed

Should we have separate issues for separate button animations ?
Also meet @siddhi-244, she is one of our mentees from PClub Summer of Code and will be contributing to this project for a month. We need to guide her throughout her contribution phase 👍 

I have advised her to add only 2-3 button animations for now so that she can work on other innovative components as well. So I'll be closing this issue for now and she'll be raising separate issues for the button animations

**Comment by theBeginner86** [comment]
> > /reviewed
> 
> Should we have separate issues for separate button animations ?
> Also meet @siddhi-244, she is one of our mentees from PClub Summer of Code and will be contributing to this project for a month. We need to guide her throughout her contribution phase 👍
> 
> I have advised her to add only 2-3 button animations for now so that she can work on other innovative components as well. So I'll be closing this issue for now and she'll be raising separate issues for the button animations

ok sure. 👍
