### ISSUE TITLE
Flip button animation 

### ISSUE THREAD

**Issue by siddhi-244** [ALPHAVIO/Mirage-UI#136]
### Feature request-
Flip button animation

### Describe how this feature will be useful to the users/ contributors-
Anybody can use this component in their website. 

#### Are you contributing under any open-source program ?

PSOC
<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by theBeginner86** [comment]
Could you please add a screenshot/demo-video as well in the issue?

**Comment by siddhi-244** [comment]
https://user-images.githubusercontent.com/69195262/124458993-4d3e3280-ddab-11eb-9ab2-d699bc106f5b.mp4

**Comment by siddhi-244** [comment]
@theBeginner86

**Comment by theBeginner86** [comment]
> index.html.-.Google.Chrome.2021-07-05.14-43-081.mp4

@siddhi-244 isn't it the same as #138 which you raised?

**Comment by siddhi-244** [comment]
I am sorry I uploaded wrong video

**Comment by siddhi-244** [comment]
I will upload again

**Comment by siddhi-244** [comment]
https://user-images.githubusercontent.com/69195262/124459812-33511f80-ddac-11eb-920c-0358f9d02d7b.mp4

**Comment by siddhi-244** [comment]
@theBeginner86

**Comment by theBeginner86** [comment]
> Screen_Recording_20210704-200917_One.UI.Home1.mp4

looks cool 👍

**Comment by siddhi-244** [comment]
Thank you ! Shall I work on it ?

**Comment by theBeginner86** [comment]
Yeah, go ahead.
