### ISSUE TITLE
Slide top border Hover stylesheet linking

### ISSUE THREAD

**Issue by puneetkaur2929** [ALPHAVIO/Mirage-UI#137]
### **Describe the bug**
Slide top border hover stylesheet linking error

### **To Reproduce**
1. Go to Slidetopborder
2. Click on index.html
3. Scroll down to link stylesheet

### **Expected behavior**
Button should show desired hover effect on hovering.

#### Are you contributing under any open-source program ?

LGM SOC '21
<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by theBeginner86** [comment]
Thanks, for pointing it out. 👍

#### Please from next time, type the name of the program as `LGM-SOC` (instead of LGM SOC '21)  so that the bot can automatically apply the required labels. This is clearly mentioned in the comments of the issue template.
