### ISSUE TITLE
Add SVG bouncing animation component

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/Mirage-UI#14]
### Feature request-
Add SVG bouncing animation component

https://user-images.githubusercontent.com/54665036/120939079-c4909000-c733-11eb-9e0d-12634492a79a.mp4

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by nitishapiplani** [comment]
I will like to work on it

**Comment by theBeginner86** [comment]
## Please comment within a day, if you are still working on this issue. If we don't get the response then we have to unassign this issue and give other contributors a chance. 😊🙂

**Comment by nitishapiplani** [comment]
Yess I am working on it as I had my vaccination I am not well that's why not able to complete so if you want you can assign to someone else

**Comment by theBeginner86** [comment]
> Yess I am working on it as I had my vaccination I am not well that's why not able to complete so if you want you can assign to someone else

No problem. 
You may take your time. 
Sorry! I was not knowing that. Take rest as well.

**Comment by nitishapiplani** [comment]
> > Yess I am working on it as I had my vaccination I am not well that's why not able to complete so if you want you can assign to someone else
> 
> No problem.
> You may take your time.
> Sorry! I was not knowing that. Take rest as well.

no need of sorry plzz assign to someone else

**Comment by Pranav016** [comment]
> > > Yess I am working on it as I had my vaccination I am not well that's why not able to complete so if you want you can assign to someone else
> > 
> > 
> > No problem.
> > You may take your time.
> > Sorry! I was not knowing that. Take rest as well.
> 
> no need of sorry plzz assign to someone else

You can yourself unassign the issue if you are not able to work. A tip for the future as well ^
Take care 🙂

**Comment by nitishapiplani** [comment]
i know that but wanted to tell u before doing something like that if i do without telling it would not be professional behaviour

**Comment by Pranav016** [comment]
> i know that but wanted to tell u before doing something like that if i do without telling it would not be professional behaviour

I think it helps us focus on reviewing the issues and PRs because it gets hectic when we need to assign and unassign so many issues so we actually appreciate if someone unassigns it by themselves 👍

**Comment by nitishapiplani** [comment]
okkay

**Comment by Pranav016** [comment]
> okkay

Plz unassign 🙂

**Comment by Sanyam17-beep** [comment]
hey @Pranav016 @nitishapiplani when will my pr reviewed i have to push this effect too

**Comment by Pranav016** [comment]
> hey @Pranav016 @nitishapiplani when will my pr reviewed i have to push this effect too

I will review it soon, you can still make a PR from a new branch. Make a new branch from 'master' and you can work on that and make a new PR.
