### ISSUE TITLE
Add smooth scrolling component

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/Mirage-UI#15]
### Feature request-
Add a component in which when you click a button on the navbar, it smoothly scrolls to that section of the webpage.
The code should be very simple and easy to use. You can make dummy sections for showing the scrolling.
Sample- 

https://user-images.githubusercontent.com/54665036/120939127-1cc79200-c734-11eb-9bf1-2ca794edf943.mp4

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by ss-sahoo** [comment]
hyy @Pranav016  can I work on this issue , as I am a participant of LGM-SOC .

**Comment by RR-Sahoo** [comment]
Hyy can I work on this issue

**Comment by theBeginner86** [comment]
> Hyy can I work on this issue

Hey @RR-Sahoo, please refer to the note at the bottom of the issue. You'll get to know how to assign it to yourself.



> ### Feature request-
> Add a component in which when you click a button on the navbar, it smoothly scrolls to that section of the webpage.
> The code should be very simple and easy to use. You can make dummy sections for showing the scrolling.
> Sample-
> 
>  1.mp4 
> 
> **Note:**
> 
> * If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
> * If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
> * It is adviced to take up/ work on only 2 issues at the same time.
> * Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by theBeginner86** [comment]
## Please comment within a day, if you are still working on this issue. If we don't get the response then we have to unassign this issue and give other contributors a chance. 😊🙂
