### ISSUE TITLE
Add scroll to top button component

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/Mirage-UI#16]
### Feature request-
Add scroll to top button component that scrolls up for you when you are in the middle or at the end of a page.
Like one on this website- https://word-nook.herokuapp.com/

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by nitishapiplani** [comment]
I will like to work on it
