### ISSUE TITLE
Add a MIT License

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/Mirage-UI#17]
### Feature request-
Add a MIT License for the repo.
Reference- https://github.com/ALPHAVIO/WordNook/blob/master/LICENSE

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by mayankmohak** [comment]
@Pranav016  made a PR #19  please review and merge under LGM-SOC 2021
