### ISSUE TITLE
Color-Scheme-Toggle Component

### ISSUE THREAD

**Issue by theBeginner86** [ALPHAVIO/Mirage-UI#189]
### Feature request-
This component should help allow the user to switch between different color schemes for a particular website depending upon the choice of the user. This would not only increase customer satisfaction but would also reduce eye strain.

### Additional context

https://user-images.githubusercontent.com/73700530/126039518-39e49a96-0eb5-4d9e-a27e-26b27d497f66.mov

#### Are you contributing under any open-source program ?

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by Sanyam17-beep** [comment]
Is this component not under lgm soc @theBeginner86

**Comment by theBeginner86** [comment]
It's under LGM SOC. Actually, I opened with an `open` label because now we are expecting contributors from other open-source programs aswell. 👍

> I'll add the label for you. 👍
