### ISSUE TITLE
Info Card Animation (React)

### ISSUE THREAD

**Issue by theBeginner86** [ALPHAVIO/Mirage-UI#191]
### Feature request-
This card hides the information until the mouse hovers onto it. Once it hovers then it reviles the info within it. This could be used on personal portfolio websites.

### Additional context

https://user-images.githubusercontent.com/73700530/126348333-871dff93-1e6c-44c3-833c-ca223ca0c6ef.mov

#### Are you contributing under any open-source program ?

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by theBeginner86** [comment]
@Anupam-Panwar I know you are working from LGMSOC but from next do mention it after you assign the issue to yourself, so that the bot can assign the label accordingly. 👍

**Comment by Anupam-Panwar** [comment]
> @Anupam-Panwar I know you are working from LGMSOC but from next do mention it after you assign the issue to yourself, so that the bot can assign the label accordingly. 👍

@theBeginner86 May you please give example because I am not clear about it. 

Is it related to a new way of assigning an issue or is there any trigger keyword for bot to assign LGM SOC label to the issue

**Comment by theBeginner86** [comment]
> > @Anupam-Panwar I know you are working from LGMSOC but from next do mention it after you assign the issue to yourself, so that the bot can assign the label accordingly. 👍
> 
> @theBeginner86 May you please give example because I am not clear about it.
> 
> Is it related to a new way of assigning an issue

No. Actually as now were expecting contributors from other open-source programs as well so we are now opening a new issue with an `open` label so that other contributors could also work on it. According to Github workflows, the LGMSOC label should be added when somebody types LGMSOC in the comment of any issue. Everything is the same as it was.
But it didn't add the label automatically when I typed LGMSOC. I think we need to look into it. 

You don't worry, I'll add the label on my own. We will take care of it. 👍

**Comment by Anupam-Panwar** [comment]
> > > @Anupam-Panwar I know you are working from LGMSOC but from next do mention it after you assign the issue to yourself, so that the bot can assign the label accordingly. 👍
> > 
> > 
> > @theBeginner86 May you please give example because I am not clear about it.
> > Is it related to a new way of assigning an issue
> 
> No. Actually as now were expecting contributors from other open-source programs as well so we are now opening a new issue with an `open` label so that other contributors could also work on it. According to Github workflows, the LGMSOC label should be added when somebody types LGMSOC in the comment of any issue. Everything is the same as it was.

Got it @theBeginner86

**Comment by Anupam-Panwar** [comment]
LGMSOC
