### ISSUE TITLE
Color Fill Card Animation (REACT)

### ISSUE THREAD

**Issue by theBeginner86** [ALPHAVIO/Mirage-UI#193]
### Feature request-
This card animation should fill the card with some color when the cursor hovers onto it. Try to make more than one card so that the effect could be more pronounced and the component can be reused much easily. This component can be used on websites for kids or other interactive websites or even on some school websites.
(You can use a better name for the component but make sure it matches with what the component is trying to do. Do discuss with us as well.)

### Additional context

https://user-images.githubusercontent.com/73700530/126354074-dd31a2e5-7099-4eac-9eeb-c5f4045117eb.mov

#### Are you contributing under any open-source program ?

(Please mention the name of the program while assigning the issue to yourself, if any)

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by bharati-21** [comment]
Hey @theBeginner86,
Would like to know if this issue is part of Hacktoberfest'21?

**Comment by bharati-21** [comment]
Hi @theBeginner86 ,
Would like to take up this issue as a part of Hacktoberfest '21.

**Comment by theBeginner86** [comment]
> Hi @theBeginner86 ,
> Would like to take up this issue as a part of Hacktoberfest '21.

Sure, go ahead!! 👍
Do read the note at the end of the issue.
You'll understand, how to assign it to yourself!!

**Comment by bharati-21** [comment]
Sure, thank you!

`/assign`

**Comment by theBeginner86** [comment]
> Sure, thank you!
> 
> `/assign`

Please done use `/assign`, just use the keyword and ignore ``. Those are used for emphasis and so that the GitHub action doesn't assign us the issue when we are creating it. From next time, please keep this in mind. Also, you may seek help from other closed issues, about how other contributors assigned the issue to themselves👍
This time, I'll assign you this issue manually. 🙂

You may start working!!

**Comment by bharati-21** [comment]
Hey @theBeginner86. Thank you :)
Sorry, my bad. This is my first time working on a repo that has actions! Usually moderators assign them right! But cool, I'll keep this in mind.


Also, how good does "animated cards" sound? I'd make it as the component name as well. (AnimatedCard.js).

**Comment by theBeginner86** [comment]
> Hey @theBeginner86. Thank you :) Sorry, my bad. This is my first time working on a repo that has actions! Usually moderators assign them right! But cool, I'll keep this in mind.
> 
> Also, how good does "animated cards" sound? I'd make it as the component name as well. (AnimatedCard.js).

No worries, we can understand. 🙌
Yeah, sure. That sounds cool. 👍

> A suggestion, please take a look at the other PRs related to react components which were merged successfully. This will help you to know what we are looking for!! 😁

**Comment by bharati-21** [comment]
Yes, I looked at other 

> > Hey @theBeginner86. Thank you :) Sorry, my bad. This is my first time working on a repo that has actions! Usually moderators assign them right! But cool, I'll keep this in mind.
> > Also, how good does "animated cards" sound? I'd make it as the component name as well. (AnimatedCard.js).
> 
> No worries, we can understand. 🙌 Yeah, sure. That sounds cool. 👍
> 
> > A suggestion, please take a look at the other PRs related to react components which were merged successfully. This will help you to know what we are looking for!! 😁

Yes, I did review other merged components!

**Comment by bharati-21** [comment]
Hi @theBeginner86, 
I have created a PR. 
Kindly review it!
