### ISSUE TITLE
Card hover animation

### ISSUE THREAD

**Issue by siddhi-244** [ALPHAVIO/Mirage-UI#198]
### Feature request-
Card hover animation

### Is your feature request related to a problem? Please describe. (optional)
No

### Describe the solution you'd like
I would like to add this animation.

### Describe how this feature will be useful to the users/ contributors-
I think users can use this to improve ui and interactivity of their website.

#### Are you contributing under any open-source program ?

PSoC
<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by riasenpai** [comment]
@siddhi-244 what type are you thinking to add? we already have a few.

**Comment by siddhi-244** [comment]
https://user-images.githubusercontent.com/69195262/127882811-a6cac3c8-bcd5-49e7-8346-f0e05629ab7c.mp4

@riasenpai some thing like this.

**Comment by riasenpai** [comment]
ok go ahead @siddhi-244 . Its a little similar to Card Pop up on hover but this works too!

**Comment by theBeginner86** [comment]
@siddhi-244, just wanted to know will you be using React or just HTML/CSS/JS? Because we have something exactly like this with React. Please check out the 
issue at: #191 
PR: #195 

But if you are not using React or the UI is different than the one in the PR, then it would be fine. 👍

**Comment by siddhi-244** [comment]
I will try with html,css
