### ISSUE TITLE
Add button animations

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/Mirage-UI#36]
### Feature request-
Add some cool animated button designs to the repository.

LGM-SOC

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by urvashiparashar** [comment]
I want to work upon this. Please assign this task @Pranav016

**Comment by Anupam-Panwar** [comment]
> I want to work upon this. Please assign this task @Pranav016

You have to type /assign to automatically get it assigned to you

**Comment by urvashiparashar** [comment]
Please review it.
