### ISSUE TITLE
Hover Effects in Navbar

### ISSUE THREAD

**Issue by theBeginner86** [ALPHAVIO/Mirage-UI#41]
### Feature request-
It should execute dropdown-like functionality on hovering. Moreover, it can also change the view of the navbar depending upon the sub-menu which is being hovered at a particular instant of time.

### Additional context

https://user-images.githubusercontent.com/73700530/121778839-70affc00-cbb6-11eb-86c0-9e0612c2c109.mov

LGM-SOC

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by Pranav016** [comment]
This is going to be a complex component to make :)
