### ISSUE TITLE
Add slide-down animation component

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/Mirage-UI#43]
### Feature request-
Add slide-down animation component

https://user-images.githubusercontent.com/54665036/121794435-97594b80-cc25-11eb-8c14-b34f9fca9369.mp4

LGM-SOC

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by Sejal2801** [comment]
I want to work on this issue, please assign it to me.

**Comment by theBeginner86** [comment]
> I want to work on this issue, please assign it to me.

Hey @Sejal2801, please have look at the note placed at the bottom of the issue. You would automatically get to know about how to assign the issue to yourself.

**Comment by riasenpai** [comment]
@PurviGoyal7 are you still working on this issue?
