### ISSUE TITLE
Add card pop-up animation on hover

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/Mirage-UI#44]
### Feature request-
When hovered over, the card pops up to reveal some information.

![image](https://user-images.githubusercontent.com/54665036/121794555-df2ca280-cc26-11eb-96d3-5c71092575bb.png)

LGM-SOC

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by bhoskarpooja** [comment]
Can I change Class names  of cards ?

**Comment by bhoskarpooja** [comment]
![Screenshot (507)](https://user-images.githubusercontent.com/72018117/121900609-3a53b780-cd43-11eb-85f2-8243a160277c.png)

I Am facing this problem while pushing my commits to my repo.
@Pranav016 please help me.

**Comment by Pranav016** [comment]
> ![Screenshot (507)](https://user-images.githubusercontent.com/72018117/121900609-3a53b780-cd43-11eb-85f2-8243a160277c.png)
> 
> I Am facing this problem while pushing my commits to my repo.
> @Pranav016 please help me.

Have you forked the repo?

**Comment by Pranav016** [comment]
> ![Screenshot (507)](https://user-images.githubusercontent.com/72018117/121900609-3a53b780-cd43-11eb-85f2-8243a160277c.png)
> 
> I Am facing this problem while pushing my commits to my repo.
> @Pranav016 please help me.

Check the branch you are pushing, you are pushing `main` but for the project the default branch is `master`. I am not sure which branch you have worked on so just check once which branch you are currently on and then push that 👍

**Comment by theBeginner86** [comment]
Since the PR has been merged so I am closing this issue.
