### ISSUE TITLE
Add Z-Image cut design component

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/Mirage-UI#45]
### Feature request-
We have a V cut design here. I think a zig-zag design would look better.
Add zig-zag image cut design component.

![image](https://user-images.githubusercontent.com/54665036/121796130-7a784480-cc34-11eb-8705-9bc6548c2d7a.png)

LGM-SOC

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by bhoskarpooja** [comment]
![Screenshot (518)](https://user-images.githubusercontent.com/72018117/122361905-5179eb80-cf75-11eb-809b-0da207fc2d8c.png)


You want this type of Zig zag?

**Comment by Pranav016** [comment]
> ![Screenshot (518)](https://user-images.githubusercontent.com/72018117/122361905-5179eb80-cf75-11eb-809b-0da207fc2d8c.png)
> 
> You want this type of Zig zag?

Yes zig Zag but only 4-5 big cuts, less cuts than in this pic

**Comment by bhoskarpooja** [comment]
ok

**Comment by Anupam-Panwar** [comment]
![image](https://user-images.githubusercontent.com/65714751/124015150-fd094e00-da01-11eb-88ba-72ed64cd6d11.png)
## Do you want something of this sort ?

**Comment by Pranav016** [comment]
> ![image](https://user-images.githubusercontent.com/65714751/124015150-fd094e00-da01-11eb-88ba-72ed64cd6d11.png)
> 
> ## Do you want something of this sort ?

Yes, different color combination would be better but the design is correct👍

**Comment by Anupam-Panwar** [comment]
Okay @Pranav016 
Got it

> > ![image](https://user-images.githubusercontent.com/65714751/124015150-fd094e00-da01-11eb-88ba-72ed64cd6d11.png)
> > ## Do you want something of this sort ?
> 
> Yes, different color combination would be better but the design is correct👍

**Comment by Pranav016** [comment]
> Okay @Pranav016
> Got it
> 
> > > ![image](https://user-images.githubusercontent.com/65714751/124015150-fd094e00-da01-11eb-88ba-72ed64cd6d11.png)
> > > ## Do you want something of this sort ?
> > 
> > 
> > Yes, different color combination would be better but the design is correct👍

You can just change the background color and color of the zig Zag design and make a PR with this.
