### ISSUE TITLE
Add open source program section to README

### ISSUE THREAD

**Issue by rishabhrathore055** [ALPHAVIO/Mirage-UI#47]

**Comment by theBeginner86** [comment]
Hey @rishabhrathore055, please don't remove the template while creating new issues. Templates help us to know the type of change contributors want.

#### So, please add the description with a screenshot/demo video about the change in readme which you want.

**Comment by rishabhrathore055** [comment]
@theBeginner86 want to add open source program section and
Contributing Guidelines

**Comment by theBeginner86** [comment]
> @theBeginner86 want to add open source program section and
> Contributing Guidelines

Please have a look at this: https://github.com/ALPHAVIO/Mirage-UI/blob/master/CONTRIBUTING.md

We already have that.

**Comment by Pranav016** [comment]
@rishabhrathore055 Add the open source program section under this issue

**Comment by swathi-469** [comment]
O would like to work on this issue please assign this to me
