### ISSUE TITLE
Add Code of conduct and License in readme file.

### ISSUE THREAD

**Issue by Shaishav0507** [ALPHAVIO/Mirage-UI#51]
### Feature request-

Hey @Pranav016 
I would like to add code of conduct and license in readme file.
Please assign it to me.
Thanks.

### Is your feature request related to a problem? Please describe. (optional)
A clear and concise description of what the problem is.

### Describe how this feature will be useful to the users/ contributors-
A clear and concise description of how this feature will be useful to our users/ contributors.

#### Are you contributing under any open-source program ?
Yes, LGM-SOC

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by Pranav016** [comment]
Is the issue about adding links to README ? Coz the files are already present..

**Comment by Shaishav0507** [comment]
Yes they are present in repo but not linked to readme file. So I wanted to link them.

**Comment by Pranav016** [comment]
> Yes they are present in repo but not linked to readme file. So I wanted to link them.

Yes, go ahead. Read the note under the issue and get the issue assigned.

**Comment by Shaishav0507** [comment]
Ok.

**Comment by Shaishav0507** [comment]
@Pranav016 please add LGMsoc label to it.

**Comment by Pranav016** [comment]
Add it above the maintainers and contributors section, in the `Note`
