### ISSUE TITLE
Add LGM-SOC'21 score card in readme.md

### ISSUE THREAD

**Issue by ishitakapoor26** [ALPHAVIO/Mirage-UI#65]
Add LGM-SOC'21 score card in readme.md

**Comment by Pranav016** [comment]
Score card? Can you give some more info on the issue?

**Comment by ishitakapoor26** [comment]
> Score card? Can you give some more info on the issue?

![score card](https://user-images.githubusercontent.com/78542333/122348548-e6c2b300-cf68-11eb-97f8-b1210303e47e.PNG)
@Pranav016 Like this

**Comment by Pranav016** [comment]
> > Score card? Can you give some more info on the issue?
> 
> ![score card](https://user-images.githubusercontent.com/78542333/122348548-e6c2b300-cf68-11eb-97f8-b1210303e47e.PNG)
> @Pranav016 Like this

I don't think this is required in the readme
