### ISSUE TITLE
Add an accordian component in react

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/Mirage-UI#71]
### Feature request-
Add an accordian component in react

LGM-SOC

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by Sanyam17-beep** [comment]
-unassign

**Comment by ujju20** [comment]
Can you explain a bit where I have to add this accordion component?

**Comment by ujju20** [comment]
Like react has Modal and navBar that way I have to add third design accordion component?

**Comment by Pranav016** [comment]
> Like react has Modal and navBar that way I have to add third design accordion component?

Yes
