### ISSUE TITLE
Add card flip animation component

### ISSUE THREAD

**Issue by Pranav016** [ALPHAVIO/Mirage-UI#9]
# Feature request-
Add card flip animation component.

https://user-images.githubusercontent.com/54665036/120903615-bcb5ea80-c664-11eb-8068-fc09da2f1b13.mp4

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by Khushi-agarwal** [comment]
@Pranav016 I would like to work on this issue.Can you please assign it to me under lgmsoc.

**Comment by Pranav016** [comment]
@akshatvirmani are you still working on this ?

**Comment by Khushi-agarwal** [comment]
@Pranav016 can I work on this?

**Comment by Pranav016** [comment]
> @Pranav016 can I work on this?

Yes I'll assign it to you if he doesn't reply.

**Comment by akshatvirmani** [comment]
I am facing difficulty in doing this. You can assign this issue to her.
