### ISSUE TITLE
Theme Clock: Light and Dark themes

### ISSUE THREAD

**Issue by Anshika-Srivastava** [ALPHAVIO/Mirage-UI#94]
**I would like to provide my code for a theme clock with both light and dark themes. You can check the preview below:**

https://user-images.githubusercontent.com/67851072/122863087-d1220480-d33f-11eb-9f7e-b30565623c5b.mp4

Please ignore the background noise!

**Please assign me this under LGMSOC'21
Thank You**

**Comment by Pranav016** [comment]
Sorry, but this component doesn't fit in the project.
