### ISSUE TITLE
add some badges and make them of single type

### ISSUE THREAD

**Issue by Umesh-01** [ALPHAVIO/Mirage-UI#97]
### Feature request-
I will add some more badges to the top of readme.md file and make them of single type so that it will look more interactive and awesome, since the badges will be colorful and more attractive than the text the users will like it and it will also help them to navigate to different sections/ webpages like PRs, issues, contributors, etc.

See this image, the badge are of different type...

![image](https://user-images.githubusercontent.com/83420185/122973761-37923b80-d3af-11eb-83db-f8ae9e385d18.png)

### Describe the solution you'd like
- I will add some more badges
- I will add links to the badges
- I will make them all of single type

### Describe how this feature will be useful to the users/ contributors-
It will help them to navigate to different sections/ web pages related to that badge.

#### Are you contributing under any open-source program ?
LGMSOC

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by Pranav016** [comment]
Which badges do you want to add ? Can you be a bit specific ? or maybe show a screenshot of a badge that you want to add

**Comment by Umesh-01** [comment]
@Pranav016 I will add badges like for closed PRs, closed issues, license, forks, etc..

**Comment by Umesh-01** [comment]
will make them of single type
will add some more badges
will add links to them, for easy navigation

**Comment by Umesh-01** [comment]
@Pranav016  should I work on this issue??

**Comment by Pranav016** [comment]
> @Pranav016 should I work on this issue??

Add a screenshot here of the badges you want to add..
After that you can work

**Comment by Umesh-01** [comment]
@Pranav016 I will add badges like this one..
and if you want me to add some specific badges then I can also do that...

![image](https://user-images.githubusercontent.com/83420185/124542056-4b727e80-de40-11eb-9c60-fc8b2256a6e2.png)

**Comment by Pranav016** [comment]
I think some of these don't look useful to the project, the ones we currently have are fine..
