### ISSUE TITLE
Drag N Drop Component

### ISSUE THREAD

**Issue by theBeginner86** [ALPHAVIO/Mirage-UI#99]
### Feature request-
Add a component that allows drag n drop functionality for pictures.

### Additional context

https://user-images.githubusercontent.com/73700530/123050231-1a488600-d41e-11eb-817b-57c682477eb9.mov

LGM-SOC

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

**Comment by Pranav016** [comment]
This component looks useful 👍 Good for reference for anyone who want to use this in their website.
A tip for those trying to implement- there is Drag and drop API in HTML so you can use that
